### ISSUE TITLE
Backup with `do_not_backup_data` fails

### ISSUE THREAD

**Issue by lapineige** [maniackcrudelis/archivist#11]
I have this issue when doing a backup with `do_not_backup_data` activated

>> Make a temporary backup for nextcloud do_not_backup_data_backup
usage: yunohost
{user,domain,app,backup,monitor,settings,service,firewall,dyndns,tools,hook,log}
...
[-h] [--no-cache] [--output-as {json,plain,none}] [--debug]
[--quiet] [--timeout ==SUPPRESS==] [--admin-password PASSWORD]
[-v]
yunohost: error: unrecognized arguments: do_not_backup_data_backup.temp
>>> The temporary backup failed...

Related to #8 ?

**Comment by maniackcrudelis** [comment]
If you know how to do it, could you add a `echo "-> app=$app"` after the line 429 https://github.com/maniackcrudelis/archivist/commit/7c8eb95fb1ed809a99107f26ad277d32b546a70c#diff-edc38723fd2d77e166ff0741c8f5222bR429
Maybe the substitution doesn't work correctly

**Comment by lapineige** [comment]
Result: `app=nextcloud`

**Comment by maniackcrudelis** [comment]
...weird...
Let's continue investigate then...
Around the line 332, could you add
```
echo "-> backup_cmd=$backup_cmd"
echo "-> backup_name=$backup_name"
```
That's strange because everything here should come from `app=${app%% *}`, line 429...

**Comment by lapineige** [comment]
I forgot: I only used archivist.sh and not my weekly backup, and it worked…

**Comment by maniackcrudelis** [comment]
But the weekly backup is just a cron that run archivist.sh
Unless you're not using archivist.sh in /opt

**Comment by lapineige** [comment]
As far as I remember, I did not change its configuration.
I did an upgrade in the mid-time, I'll wait for next weekly backup to see if the issue is still there.
