### ISSUE TITLE
Some errors in the backups

### ISSUE THREAD

**Issue by aarontrom** [maniackcrudelis/archivist#16]
Hi, 

first I'd like to appreciate archivist, as it automates the process of backups and that makes it awesome! :)

However I got a confirmation e-mail from the usual cron job from archivist and I am a bit concerned whether everything works fine or if there are some errors. That's why I open this issue here to ask. 

My config file is the following: 
[Backup_list.conf.txt](https://github.com/maniackcrudelis/archivist/files/7929317/Backup_list.conf.txt)

and the e-mail that I got is this here: 
[email.txt](https://github.com/maniackcrudelis/archivist/files/7929340/email.txt)

I would appreciate any help even if it's just about to confirm that everything is okay or, in case it's not, what things could be changed.

Plus, I would like to add that the config panel seems to not work:
![Screenshot_2022-01-25_00-06-27](https://user-images.githubusercontent.com/69819346/150880118-f14d62c2-8e27-434c-b26f-7c4f2e28d0c2.png)
This might be worth to look into as well.

**Comment by maniackcrudelis** [comment]
Hi @aarontrom

Glad you enjoy this app.

Your log is clearly not "okay".

But I'm puzzled by the fact that tar is trowing an error about the symlink, that it's not supposed to use anyway !
OK... That's on me ! You just find a obvious bug that I don't know how I even could have let pass...

About etherpad, I don't know from where the error is really coming. I can see that it complains about missing files. I couldn't say much, I guess you should try to make a regular backup of this app to see if it's working.
Same for bibliogram.

Again with friendica, those are errors from the backup scripts of the apps themselves.


As for the config-panel, I recently spotted a discussion about it that I quickly read through, as I understood it the config-panel feature was rewritten.
That's a pity, considering it was quite useful. Unfortunately, I'm not working of YunoHost app packages anymore. Just maintaining the code of my own apps.
Best would be to open a issue on https://github.com/YunoHost-Apps/archivist_ynh/issues


Meanwhile, I'm going to fix the tar issue !

**Comment by maniackcrudelis** [comment]
Fixed by https://github.com/maniackcrudelis/archivist/commit/8f5f56514786ad7da561c56f9c4f69c09ead31a7 and https://github.com/YunoHost-Apps/archivist_ynh/commit/ec15b96d819fc9c263b3d7769acde108d3c7ad83

**Comment by aarontrom** [comment]
Hi @maniackcrudelis 

thanks for your message and also that you fixed the tar issue!

Thanks also for your recommendations, I just deleted the old backups and did a new backup of these apps and they seem fine, except friendica.

And I also submitted a new issue for the config-panel: https://github.com/YunoHost-Apps/archivist_ynh/issues/45
