### ISSUE TITLE
I chose "no encryption" but can't follow with password field left empty

### ISSUE THREAD

**Issue by ImaCrea** [maniackcrudelis/archivist#5]
It's pretty much all in the title :)
Thank you so much for this great work! I'll use it encrypted for now. cheers

**Comment by maniackcrudelis** [comment]
Hi ImaCrea

That's more an issue for https://github.com/YunoHost-Apps/archivist_ynh than for this repo, but that doesn't really matter.
Could you tell me what's your version of YunoHost ? And what is the error message ? Is it about the size or the low security of the password ?
