### ISSUE TITLE
Encrypted backups not sent

### ISSUE THREAD

**Issue by bhdouglass** [maniackcrudelis/archivist#7]
I've setup encrypted backups and I'm using the local and b2 senders. Neither sender is sending the encrypted backups but I can see `Encrypt backups` in the log output. I assume the local sender does this on purpose, but I'm wondering if the b2 sender is missing something.

**Comment by maniackcrudelis** [comment]
Both scripts are supposed to send your backups to another place, whether they're encrypted or not.
Is your config file correct ?

**Comment by bhdouglass** [comment]
This is what I have for encryption related options in my config file:

```
backup_dir=/home/yunohost.app/archivist/backup
enc_backup_dir=/home/yunohost.app/archivist/encrypted_backup
encrypt=true
cryptpass=/opt/yunohost/archivist/passkey
```

And `/opt/yunohost/archivist/passkey` contains the password I specified in plain text.

**Comment by maniackcrudelis** [comment]
It would be more about the recipient config part.

**Comment by bhdouglass** [comment]
Ah ok, I've got `encrypt=false` for the local sender. That's fine. But for b2 I have:

```
> recipient name=b2 sync          
type=b2
destination directory=backup
encrypt=true 
b2_bucket=xyz
pre_backup=
post_backup=
exclude backup=
include backup=
```

**Comment by maniackcrudelis** [comment]
Do you have a log of the operation ?
And, as you write this sender, do you know how it's supposed to work ?

**Comment by bhdouglass** [comment]
Here is the log: [archivist.log](https://github.com/maniackcrudelis/archivist/files/3773005/archivist.log)

The b2 sender should work similar to the rsync one. You point the `b2` command at a directory and sync it to b2.

**Comment by maniackcrudelis** [comment]
The log about b2 is hard to read, but looks like it works (regarding b2) but with non encrypted files though.

But, having a look to the code, https://github.com/maniackcrudelis/archivist/blob/master/archivist.sh#L548, it should work as expected.
But, looks like there's an ending space on this line in your config file !

**Comment by bhdouglass** [comment]
ha! That worked! Thank you!

Just one last question, are there docs for how to restore an encrypted backup?

**Comment by maniackcrudelis** [comment]
If you ask I guess not.
And indeed, there's not any...
For sure would be better to have one !

I already did do that myself once, it's quite easy, you just have to install encfs and mount the encrypted directory.
But yes, would be better to have a proper documentation... But I lack time for that...

**Comment by bhdouglass** [comment]
👍 I'll try that out and maybe make a PR if I get the chance. Thank you again!
