### ISSUE TITLE
How can I create a Core Only backup ?

### ISSUE THREAD

**Issue by lapineige** [maniackcrudelis/archivist#8]
It seems this (awesome :) tool backup my whole Nextcloud. How can I tell it to backup only the core ?

Thanks :)

**Comment by maniackcrudelis** [comment]
Fixed by https://github.com/maniackcrudelis/archivist/commit/7c8eb95fb1ed809a99107f26ad277d32b546a70c
Add `do_not_backup_data` after an app to not backup the data.

An upgrade of archivist_ynh is coming.
